/**
 * JS mirror of every ENUM in Document 4 (Database Design v1.1).
 * Keep this file and the frozen schema in sync manually — no code should
 * hardcode these string literals anywhere else.
 */
module.exports = {
  TOKEN_TYPE: { PASSWORD_RESET: 'PASSWORD_RESET', EMAIL_VERIFICATION: 'EMAIL_VERIFICATION' },

  CONDITION_TYPE: { PRICE_ABOVE: 'PRICE_ABOVE', PRICE_BELOW: 'PRICE_BELOW' },

  PRICE_SOURCE: {
    MANUAL: 'MANUAL',
    GOVERNMENT_DATASET: 'GOVERNMENT_DATASET',
    THIRD_PARTY_API: 'THIRD_PARTY_API',
    SUPPLIER_INTEGRATION: 'SUPPLIER_INTEGRATION',
    WEB_SCRAPE: 'WEB_SCRAPE',
  },

  NOTIFICATION_CHANNEL: { EMAIL: 'EMAIL' },

  DELIVERY_STATUS: { PENDING: 'PENDING', SENT: 'SENT', FAILED: 'FAILED' },

  DEPENDENCY_TYPE: {
    DRIVES_COST: 'DRIVES_COST',
    INFLUENCES: 'INFLUENCES',
    CORRELATES_WITH: 'CORRELATES_WITH',
  },

  KB_ENTITY_TYPE: {
    RAW_MATERIAL: 'RAW_MATERIAL',
    COST_DRIVER: 'COST_DRIVER',
    EXTERNAL_FACTOR: 'EXTERNAL_FACTOR',
  },

  // Phase A (PRICE_INGESTION), Phase G (NEWS_INGESTION), Phase H (AI_INSIGHTS).
  JOB_TYPE: {
    PRICE_INGESTION: 'PRICE_INGESTION',
    NEWS_INGESTION: 'NEWS_INGESTION',
    AI_INSIGHTS: 'AI_INSIGHTS',
  },

  JOB_STATUS: { SUCCESS: 'SUCCESS', FAILED: 'FAILED' },

  DIGEST_FREQUENCY: { DAILY: 'DAILY', WEEKLY: 'WEEKLY', MONTHLY: 'MONTHLY' },

  // Phase H — AI Market Intelligence Agent.
  // Mirrors ENUM columns in ai_insights table (migration 020).
  // Must stay in sync with the DB ENUM definition.
  OUTLOOK: {
    BEARISH:  'BEARISH',
    NEUTRAL:  'NEUTRAL',
    BULLISH:  'BULLISH',
    VOLATILE: 'VOLATILE',
  },

  INSIGHT_CONFIDENCE: {
    LOW:    'LOW',
    MEDIUM: 'MEDIUM',
    HIGH:   'HIGH',
  },
};
